"""Auto-derived HS keyword aliases.

GENERATED FILE — do not hand-edit.  Regenerate via:

    python scripts/generate_hs_keywords_auto.py

Source layers (deterministic, in order — same as the seed-time merge):

  Tier 2  Canonical material name + symbol/code (when ≥2 chars)
  Tier 3  Supply-chain stage label + stage-specific generic terms
          (ore / concentrate / refined / metal / scrap / etc.)
  Tier 4  Tokens extracted from the partner-curated
          "Comprehensive HS_HTS codes" CSV's Description column,
          split on punctuation (em-dashes, parens, semicolons),
          lowercased, deduped.

These are MERGED with the hand-curated ``_HS_KEYWORDS_BY_MAPPING`` from
``seed_hs_mappings.py`` (Tier 1) at seed time — hand-curated keywords
appear first in each array so they win on lookup priority.

Why split into a separate file: the merged dict is ~284 entries × ~8
keywords each.  Inline in seed_hs_mappings.py it would balloon that
file by ~2,800 lines and obscure the partner-curated content.  Living
here lets the seed file stay readable while the auto-derived breadth
sits in one greppable place.

Confidence note (text-matching event attribution):
  Some keywords appear in many entries ("metal" → 73, "ore" → 59,
  "battery grade" → 36).  These low-specificity tokens are useful for
  stage-rolling but get down-weighted by inverse-frequency scoring
  inside ``normalizers.material_resolver.MaterialCache.build()``:

      relevance(kw) = 0.90 / sqrt(N_mappings_containing_kw)

  Result: ``"lithium hydroxide monohydrate"`` (in 1 mapping) keeps
  full 0.90 relevance; ``"metal"`` (in 73) drops to ~0.105.  Square
  root softens the decay so generic tokens stay informative when
  they're the only signal.
"""

from __future__ import annotations


_HS_KEYWORDS_AUTO: dict[tuple[str, str], list[str]] = {
    ("2504", "Natural Graphite"): [
        'natural graphite',
        'ore and concentrates',
        'natural graphite, in powder or flakes',
        'natural graphite, other',
        'graphite, natural, other',
    ],
    ("250410", "Natural Graphite"): [
        'natural graphite',
        'ore and concentrates',
        'natural graphite, in powder or flakes',
        'natural graphite, other',
    ],
    ("250490", "Natural Graphite"): [
        'natural graphite',
        'ore and concentrates',
        'graphite, natural, other',
    ],
    ("2510", "Phosphate (Battery Grade)"): [
        'phosphate (battery grade)',
        'ore and concentrates',
        'natural calcium phosphates, unground',
        'natural calcium phosphates, ground',
    ],
    ("251010", "Phosphate (Battery Grade)"): [
        'phosphate (battery grade)',
        'ore and concentrates',
        'natural calcium phosphates, unground',
    ],
    ("251020", "Phosphate (Battery Grade)"): [
        'phosphate (battery grade)',
        'ore and concentrates',
        'natural calcium phosphates, ground',
    ],
    ("2519", "Magnesium"): [
        'magnesium',
        'mg',
        'ore and concentrates',
    ],
    ("251910", "Magnesium"): [
        'magnesium',
        'mg',
        'ore and concentrates',
    ],
    ("251990", "Magnesium"): [
        'magnesium',
        'mg',
    ],
    ("2528", "Boron"): [
        'boron',
        'ore and concentrates',
        'natural borates',
        'sodium',
        'ulexite',
        'calcium',
        'colemanite',
    ],
    ("252800", "Boron"): [
        'boron',
        'ore and concentrates',
        'natural borates',
        'sodium',
        'ulexite',
        'calcium',
        'colemanite',
    ],
    # 2026-06-11: removed ("252810","Boron") and ("252890","Boron") — both
    # codes were collapsed into 252800 in HS2022 audit; entries orphaned.
    ("2529", "Fluorspar"): [
        'fluorspar',
        'ore and concentrates',
        'fluorspar, metallurgical grade',
        'fluorspar, acid grade',
    ],
    ("252921", "Fluorspar"): [
        'fluorspar',
        'ore and concentrates',
        'fluorspar, metallurgical grade',
    ],
    ("252922", "Fluorspar"): [
        'fluorspar',
        'fluorspar, acid grade',
    ],
    ("2530", "Fluorspar"): [
        'fluorspar',
        'ore and concentrates',
        'natural cryolite',
    ],
    ("253020", "Magnesium"): [
        'magnesium',
        'mg',
        'ore and concentrates',
    ],
    ("253090", "Fluorspar"): [
        'fluorspar',
        'ore and concentrates',
        'natural cryolite',
    ],
    ("2601", "Iron Ore (LFP Grade)"): [
        'iron ore (lfp grade)',
        'fe',
        'ore and concentrates',
        'iron ores',
        'coarse',
        'pellets',
        'briquettes',
        'sinter',
        'roasted iron pyrites',
    ],
    ("260111", "Iron Ore (LFP Grade)"): [
        'iron ore (lfp grade)',
        'fe',
        'ore and concentrates',
        'iron ores',
        'coarse',
    ],
    ("260112", "Iron Ore (LFP Grade)"): [
        'iron ore (lfp grade)',
        'fe',
        'ore and concentrates',
        'iron ores',
        'pellets',
        'briquettes',
        'sinter',
    ],
    ("260120", "Iron Ore (LFP Grade)"): [
        'iron ore (lfp grade)',
        'fe',
        'roasted iron pyrites',
    ],
    ("2602", "Manganese"): [
        'manganese',
        'mn',
        'ore and concentrates',
        'manganese ores <47% mn',
        'manganese ores ≥47% mn',
    ],
    ("260200", "Manganese"): [
        'manganese',
        'mn',
        'ore and concentrates',
        'manganese ores <47% mn',
        'manganese ores ≥47% mn',
    ],
    ("2603", "Copper"): [
        'copper',
        'cu',
        'ore and concentrates',
        'copper ore and concentrates',
    ],
    ("260300", "Copper"): [
        'copper',
        'cu',
        'ore and concentrates',
        'copper ore and concentrates',
    ],
    ("2604", "Nickel"): [
        'nickel',
        'ni',
        'ore and concentrates',
        'nickel ores and concentrates, nickel content',
    ],
    ("260400", "Nickel"): [
        'nickel',
        'ni',
        'ore and concentrates',
        'nickel ores and concentrates, nickel content',
    ],
    ("2605", "Cobalt"): [
        'cobalt',
        'co',
        'ore and concentrates',
        'cobalt ores and concentrates',
    ],
    ("260500", "Cobalt"): [
        'cobalt',
        'co',
        'ore and concentrates',
        'cobalt ores and concentrates',
    ],
    ("2606", "Aluminum"): [
        'aluminum',
        'al',
        'ore and concentrates',
    ],
    ("260600", "Aluminum"): [
        'aluminum',
        'al',
        'ore and concentrates',
    ],
    ("2608", "Zinc"): [
        'zinc',
        'zn',
        'ore and concentrates',
        'zinc ores and concentrates, zinc content',
    ],
    ("260800", "Zinc"): [
        'zinc',
        'zn',
        'ore and concentrates',
        'zinc ores and concentrates, zinc content',
    ],
    ("2609", "Tin"): [
        'tin',
        'sn',
        'ore and concentrates',
    ],
    ("2610", "Chromium"): [
        'chromium',
        'cr',
        'ore and concentrates',
        'chromium ores ≤40% cr₂o₃',
        'chromium ores 40',
        '46% cr₂o₃',
        'chromium ores ≥46% cr₂o₃',
    ],
    ("261000", "Chromium"): [
        'chromium',
        'cr',
        'ore and concentrates',
        'chromium ores ≤40% cr₂o₃',
        'chromium ores 40',
        '46% cr₂o₃',
        'chromium ores ≥46% cr₂o₃',
    ],
    ("2611", "Tungsten"): [
        'tungsten',
        'ore and concentrates',
        'tungsten ores',
        'tungsten concentrates',
    ],
    ("261100", "Tungsten"): [
        'tungsten',
        'ore and concentrates',
        'tungsten ores',
        'tungsten concentrates',
    ],
    ("2613", "Molybdenum"): [
        'molybdenum',
        'mo',
        'ore and concentrates',
        'molybdenum ore and concentrates, roasted',
        'molybdenum ore and concentrates, other',
    ],
    ("261310", "Molybdenum"): [
        'molybdenum',
        'mo',
        'molybdenum ore and concentrates, roasted',
    ],
    ("261390", "Molybdenum"): [
        'molybdenum',
        'mo',
        'ore and concentrates',
        'molybdenum ore and concentrates, other',
    ],
    ("2614", "Titanium"): [
        'titanium',
        'ti',
        'ore and concentrates',
        'synthetic rutile',
        'ilmenite and ilmenite sand',
        'rutile concentrate',
    ],
    ("261400", "Titanium"): [
        'titanium',
        'ti',
        'ore and concentrates',
        'synthetic rutile',
        'ilmenite and ilmenite sand',
        'rutile concentrate',
    ],
    ("2615", "Niobium"): [
        'niobium',
        'nb',
        'ore and concentrates',
        'synthetic tantalum‑niobium concentrates',
        'niobium ores and concentrates',
    ],
    ("2615", "Tantalum"): [
        'tantalum',
        'ta',
        'ore and concentrates',
        'synthetic tantalum‑niobium concentrates',
        'tantalum ores and concentrates',
    ],
    ("2615", "Vanadium"): [
        'vanadium',
        'ore and concentrates',
        'vanadium ores and concentrates',
    ],
    ("2615", "Zirconium"): [
        'zirconium',
        'zr',
        'ore and concentrates',
        'zirconium ores and concentrates',
    ],
    ("261510", "Zirconium"): [
        'zirconium',
        'zr',
        'ore and concentrates',
        'zirconium ores and concentrates',
    ],
    ("261590", "Niobium"): [
        'niobium',
        'nb',
        'ore and concentrates',
        'synthetic tantalum‑niobium concentrates',
        'niobium ores and concentrates',
    ],
    ("261590", "Tantalum"): [
        'tantalum',
        'ta',
        'ore and concentrates',
        'synthetic tantalum‑niobium concentrates',
        'tantalum ores and concentrates',
    ],
    ("261590", "Vanadium"): [
        'vanadium',
        'ore and concentrates',
        'vanadium ores and concentrates',
    ],
    ("2616", "Platinum-Group Metals"): [
        'platinum-group metals',
        'pgm',
        'ore and concentrates',
    ],
    ("2616", "Silver"): [
        'silver',
        'ag',
        'ore and concentrates',
        'silver ores and concentrates',
    ],
    ("2617", "Antimony"): [
        'antimony',
        'sb',
        'ore and concentrates',
    ],
    ("2617", "Rare Earth Elements"): [
        'rare earth elements',
        'ree',
        'ore and concentrates',
    ],
    ("261710", "Antimony"): [
        'antimony',
        'sb',
        'ore and concentrates',
    ],
    ("261790", "Rare Earth Elements"): [
        'rare earth elements',
        'ree',
        'ore and concentrates',
    ],
    ("262040", "Vanadium"): [
        'vanadium',
        'vanadium‑bearing ash and residues',
    ],
    ("262099", "Titanium"): [
        'titanium',
        'ti',
        'titanium slag',
    ],
    ("262099", "Vanadium"): [
        'vanadium',
        'vanadium‑bearing ash and residues, other',
    ],
    ("2804", "Selenium"): [
        'selenium',
        'se',
    ],
    ("2804", "Silicon (Anode Grade)"): [
        'silicon (anode grade)',
        'si',
        'silicon, containing by weight 99.99% or more of silicon',
        'silicon, containing by weight ≥99.00% but <99.99% silicon',
    ],
    ("2804", "Tellurium"): [
        'tellurium',
        'te',
    ],
    ("280461", "Silicon (Anode Grade)"): [
        'silicon (anode grade)',
        'si',
        'silicon, containing by weight 99.99% or more of silicon',
    ],
    ("280469", "Silicon (Anode Grade)"): [
        'silicon (anode grade)',
        'si',
        'silicon, containing by weight ≥99.00% but <99.99% silicon',
    ],
    ("2805", "Dysprosium"): [
        'dysprosium',
        'dy',
        'rare‑earth metals, scandium and yttrium, whether or not intermixed or interalloyed',
        'including dysprosium',
    ],
    ("2805", "Lithium"): [
        'lithium',
        'li',
    ],
    ("2805", "Neodymium"): [
        'neodymium',
        'nd',
    ],
    ("2805", "Praseodymium"): [
        'praseodymium',
        'pr',
    ],
    ("2805", "Rare Earth Elements"): [
        'rare earth elements',
        'ree',
        'rare‑earth metals, scandium and yttrium, whether or not intermixed or interalloyed',
        'rare‑earth metals, scandium and yttrium, not alloyed',
        'rare‑earth metals, scandium and yttrium, alloyed',
    ],
    ("2805", "Terbium"): [
        'terbium',
        'tb',
        'rare‑earth metals, scandium and yttrium, whether or not intermixed or interalloyed',
    ],
    ("280530", "Dysprosium"): [
        'dysprosium',
        'dy',
        'rare‑earth metals, scandium and yttrium, whether or not intermixed or interalloyed',
        'including dysprosium',
    ],
    ("280530", "Neodymium"): [
        'neodymium',
        'nd',
    ],
    ("280530", "Praseodymium"): [
        'praseodymium',
        'pr',
    ],
    ("280530", "Rare Earth Elements"): [
        'rare earth elements',
        'ree',
        'rare‑earth metals, scandium and yttrium, whether or not intermixed or interalloyed',
        'rare‑earth metals, scandium and yttrium, not alloyed',
        'rare‑earth metals, scandium and yttrium, alloyed',
    ],
    ("280530", "Terbium"): [
        'terbium',
        'tb',
        'rare‑earth metals, scandium and yttrium, whether or not intermixed or interalloyed',
    ],
    ("2809", "Phosphate (Battery Grade)"): [
        'phosphate (battery grade)',
        'battery grade',
        'battery-grade',
        'high purity',
    ],
    ("280920", "Phosphate (Battery Grade)"): [
        'phosphate (battery grade)',
        'battery grade',
        'battery-grade',
        'high purity',
    ],
    ("2810", "Boron"): [
        'boron',
        'boric acids',
    ],
    ("281000", "Boron"): [
        'boron',
        'boric acids',
    ],
    ("2811", "Fluorspar"): [
        'fluorspar',
        'hydrofluoric acid',
    ],
    ("281111", "Fluorspar"): [
        'fluorspar',
        'hydrofluoric acid',
    ],
    ("2815", "Sodium"): [
        'sodium',
        'na',
        'sodium hydroxide',
        'solid',
        'caustic soda',
    ],
    ("281511", "Sodium"): [
        'sodium',
        'na',
        'sodium hydroxide',
        'solid',
        'caustic soda',
    ],
    ("281512", "Sodium"): [
        'sodium',
        'na',
    ],
    ("281610", "Magnesium"): [
        'magnesium',
        'mg',
        'magnesium hydroxide',
        'peroxide',
    ],
    ("2817", "Zinc"): [
        'zinc',
        'zn',
        'battery grade',
        'battery-grade',
        'high purity',
        'zinc oxide',
        'zinc peroxide',
    ],
    ("281700", "Zinc"): [
        'zinc',
        'zn',
        'battery grade',
        'battery-grade',
        'high purity',
        'zinc oxide',
        'zinc peroxide',
    ],
    ("281820", "Aluminum"): [
        'aluminum',
        'al',
    ],
    ("2820", "Manganese"): [
        'manganese',
        'mn',
        'battery grade',
        'battery-grade',
        'high purity',
        'manganese dioxide',
    ],
    ("282010", "Manganese"): [
        'manganese',
        'mn',
        'battery grade',
        'battery-grade',
        'high purity',
        'manganese dioxide',
    ],
    ("2822", "Cobalt"): [
        'cobalt',
        'co',
        'battery grade',
        'battery-grade',
        'high purity',
        'cobalt oxides and hydroxides',
        'cobalt oxides and hydroxides, other',
    ],
    ("282200", "Cobalt"): [
        'cobalt',
        'co',
        'cobalt oxides and hydroxides',
        'cobalt oxides and hydroxides, other',
    ],
    ("2823", "Titanium"): [
        'titanium',
        'ti',
        'battery grade',
        'battery-grade',
        'high purity',
        'titanium oxides',
        'unfinished tio₂ pigments',
    ],
    ("282300", "Titanium"): [
        'titanium',
        'ti',
        'titanium oxides',
        'unfinished tio₂ pigments',
    ],
    ("2825", "Lithium"): [
        'lithium',
        'li',
        'battery grade',
        'battery-grade',
        'high purity',
        'lithium oxide and hydroxide',
    ],
    ("2825", "Vanadium"): [
        'vanadium',
        'battery grade',
        'battery-grade',
        'high purity',
        'vanadium pentoxide',
        'vanadium anhydride',
        'vanadium oxides and hydroxides, other',
    ],
    ("282520", "Lithium"): [
        'lithium',
        'li',
        'battery grade',
        'battery-grade',
        'high purity',
        'lithium oxide and hydroxide',
    ],
    ("282530", "Vanadium"): [
        'vanadium',
        'vanadium pentoxide',
        'vanadium anhydride',
        'vanadium oxides and hydroxides, other',
    ],
    ("282560", "Germanium"): [
        'germanium',
        'ge',
        'germanium dioxide',
        'other germanium oxides',
    ],
    ("282560", "Zirconium"): [
        'zirconium',
        'zr',
        'zirconium compounds',
    ],
    ("282570", "Molybdenum"): [
        'molybdenum',
        'mo',
        'molybdenum oxides and hydroxides',
    ],
    ("282580", "Antimony"): [
        'antimony',
        'sb',
        'antimony oxide',
    ],
    ("282590", "Niobium"): [
        'niobium',
        'nb',
        'niobium oxide',
    ],
    ("282590", "Tantalum"): [
        'tantalum',
        'ta',
        'tantalum oxide',
    ],
    ("282590", "Tungsten"): [
        'tungsten',
        'tungsten oxides',
    ],
    ("2826", "Fluorspar"): [
        'fluorspar',
        'aluminum fluoride',
        'synthetic cryolite',
    ],
    ("282612", "Fluorspar"): [
        'fluorspar',
        'aluminum fluoride',
    ],
    ("282630", "Fluorspar"): [
        'fluorspar',
        'synthetic cryolite',
    ],
    ("282690", "Tantalum"): [
        'tantalum',
        'ta',
        'potassium fluorotantalate',
    ],
    ("2827", "Magnesium"): [
        'magnesium',
        'mg',
        'magnesium chloride',
    ],
    ("282731", "Magnesium"): [
        'magnesium',
        'mg',
        'magnesium chloride',
    ],
    ("282739", "Germanium"): [
        'germanium',
        'ge',
        'germanium chlorides',
    ],
    ("282739", "Lithium"): [
        'lithium',
        'li',
    ],
    ("2833", "Cobalt"): [
        'cobalt',
        'co',
        'battery grade',
        'battery-grade',
        'high purity',
        'cobalt sulfates',
    ],
    ("283321", "Magnesium"): [
        'magnesium',
        'mg',
        'magnesium sulfate',
    ],
    ("283324", "Nickel"): [
        'nickel',
        'ni',
        'battery grade',
        'battery-grade',
        'high purity',
    ],
    ("283329", "Cobalt"): [
        'cobalt',
        'co',
        'battery grade',
        'battery-grade',
        'high purity',
        'cobalt sulfates',
    ],
    ("283329", "Manganese"): [
        'manganese',
        'mn',
        'battery grade',
        'battery-grade',
        'high purity',
    ],
    ("283329", "Zinc"): [
        'zinc',
        'zn',
        'battery grade',
        'battery-grade',
        'high purity',
        'zinc sulfate',
    ],
    ("2835", "Sodium"): [
        'sodium',
        'na',
        'battery grade',
        'battery-grade',
        'high purity',
        'sodium phosphates, tribasic',
        'trisodium phosphate',
    ],
    ("2836", "Cobalt"): [
        'cobalt',
        'co',
        'battery grade',
        'battery-grade',
        'high purity',
        'cobalt carbonates',
    ],
    ("2836", "Lithium"): [
        'lithium',
        'li',
        'battery grade',
        'battery-grade',
        'high purity',
        'lithium carbonate, pharma grade',
        'lithium carbonate, other',
    ],
    ("2836", "Sodium"): [
        'sodium',
        'na',
        'battery grade',
        'battery-grade',
        'high purity',
        'sodium carbonate',
    ],
    ("283620", "Sodium"): [
        'sodium',
        'na',
        'battery grade',
        'battery-grade',
        'high purity',
        'sodium carbonate',
    ],
    ("283691", "Lithium"): [
        'lithium',
        'li',
        'battery grade',
        'battery-grade',
        'high purity',
        'lithium carbonate, pharma grade',
        'lithium carbonate, other',
    ],
    ("283699", "Cobalt"): [
        'cobalt',
        'co',
        'cobalt carbonates',
    ],
    ("283699", "Zirconium"): [
        'zirconium',
        'zr',
        'other carbonates',
        'zirconium compounds',
    ],
    ("2840", "Boron"): [
        'boron',
        'battery grade',
        'battery-grade',
        'high purity',
        'borates, refined borax',
        'anhydrous',
        'non‑anhydrous',
    ],
    ("284011", "Boron"): [
        'boron',
        'battery grade',
        'battery-grade',
        'high purity',
        'borates, refined borax',
        'anhydrous',
    ],
    ("284019", "Boron"): [
        'boron',
        'battery grade',
        'battery-grade',
        'high purity',
        'borates, refined borax',
        'non‑anhydrous',
    ],
    ("2841", "Rhenium"): [
        'rhenium',
        're',
        'salts of peroxometallic acids',
        'ammonium perrhenate',
    ],
    ("2841", "Sodium"): [
        'sodium',
        'na',
        'battery grade',
        'battery-grade',
        'high purity',
        'other salts of oxometallic or peroxometallic acids, sodium salts',
        'other oxometallic and peroxometallic acid salts',
    ],
    ("284170", "Molybdenum"): [
        'molybdenum',
        'mo',
        'molybdates of ammonium',
        'molybdates, all others',
    ],
    ("284180", "Tungsten"): [
        'tungsten',
        'ammonium tungstates',
    ],
    ("284190", "Rhenium"): [
        'rhenium',
        're',
        'salts of peroxometallic acids',
        'ammonium perrhenate',
    ],
    ("2846", "Dysprosium"): [
        'dysprosium',
        'dy',
        'battery grade',
        'battery-grade',
        'high purity',
        'other rare‑earth compounds: oxides or chlorides',
        'compounds of gadolinium, terbium or dysprosium',
        'compounds of mixtures of rare‑earth metals',
    ],
    ("2846", "Neodymium"): [
        'neodymium',
        'nd',
        'battery grade',
        'battery-grade',
        'high purity',
        'other rare‑earth compounds: oxides or chlorides',
        'compounds of praseodymium, neodymium or samarium',
        'compounds of mixtures of rare‑earth metals',
    ],
    ("2846", "Praseodymium"): [
        'praseodymium',
        'pr',
        'battery grade',
        'battery-grade',
        'high purity',
        'other rare‑earth compounds: oxides or chlorides',
        'other rare‑earth compounds: other',
        'other rare‑earth compounds: other, mixtures',
    ],
    ("2846", "Rare Earth Elements"): [
        'rare earth elements',
        'ree',
        'battery grade',
        'battery-grade',
        'high purity',
        'cerium compounds',
        'other rare‑earth compounds: oxides or chlorides',
        'other rare‑earth compounds: carbonates',
        'other rare‑earth compounds: oxides',
        'other rare‑earth compounds: chlorides',
        'other rare‑earth compounds: other',
    ],
    ("2846", "Terbium"): [
        'terbium',
        'tb',
        'battery grade',
        'battery-grade',
        'high purity',
        'other rare‑earth compounds: oxides or chlorides',
        'other rare‑earth compounds: carbonates',
        'other rare‑earth compounds: other',
    ],
    ("284610", "Rare Earth Elements"): [
        'rare earth elements',
        'ree',
        'cerium compounds',
    ],
    ("284690", "Dysprosium"): [
        'dysprosium',
        'dy',
        'other rare‑earth compounds: oxides or chlorides',
        'compounds of gadolinium, terbium or dysprosium',
        'compounds of mixtures of rare‑earth metals',
    ],
    ("284690", "Neodymium"): [
        'neodymium',
        'nd',
        'other rare‑earth compounds: oxides or chlorides',
        'compounds of praseodymium, neodymium or samarium',
        'compounds of mixtures of rare‑earth metals',
    ],
    ("284690", "Praseodymium"): [
        'praseodymium',
        'pr',
        'other rare‑earth compounds: oxides or chlorides',
        'other rare‑earth compounds: other',
        'other rare‑earth compounds: other, mixtures',
    ],
    ("284690", "Rare Earth Elements"): [
        'rare earth elements',
        'ree',
        'other rare‑earth compounds: oxides or chlorides',
        'other rare‑earth compounds: carbonates',
        'other rare‑earth compounds: oxides',
        'other rare‑earth compounds: chlorides',
        'other rare‑earth compounds: other',
    ],
    ("284690", "Terbium"): [
        'terbium',
        'tb',
        'other rare‑earth compounds: oxides or chlorides',
        'other rare‑earth compounds: carbonates',
        'other rare‑earth compounds: other',
    ],
    ("284990", "Tungsten"): [
        'tungsten',
        'tungsten carbides',
    ],
    ("285390", "Gallium"): [
        'gallium',
        'ga',
        'gallium arsenide wafers, undoped',
    ],
    ("291529", "Cobalt"): [
        'cobalt',
        'co',
        'cobalt acetates',
    ],
    ("320611", "Titanium"): [
        'titanium',
        'ti',
        'tio₂ pigments, containing 80% or more tio₂',
    ],
    ("320619", "Titanium"): [
        'titanium',
        'ti',
        'tio₂ pigments, other',
    ],
    ("320620", "Molybdenum"): [
        'molybdenum',
        'mo',
        'molybdenum pigments, molybdenum orange',
    ],
    ("381800", "Gallium"): [
        'gallium',
        'ga',
        'gallium arsenide wafers, doped',
    ],
    ("7106", "Silver"): [
        'silver',
        'ag',
        'silver, unwrought, bullion',
        'silver, unwrought, dore',
    ],
    ("7110", "Platinum-Group Metals"): [
        'platinum-group metals',
        'pgm',
        'platinum, unwrought or in powder form',
        'platinum, semi‑manufactured forms',
        'palladium, unwrought or in powder form',
        'palladium, semi‑manufactured forms',
        'rhodium, unwrought or in powder form',
        'rhodium, semi‑manufactured forms',
        'iridium, unwrought or in powder form',
        'ruthenium, unwrought or in powder form',
        'osmium, unwrought or in powder form',
    ],
    ("7202", "Chromium"): [
        'chromium',
        'cr',
        'ferrochromium >4% carbon',
        'ferrochromium 3',
        '4% carbon',
        'ferrochromium 0.5',
        '3% carbon',
        'ferrochromium ≤0.5% carbon',
        'ferrosilicon chromium',
    ],
    ("7202", "Manganese"): [
        'manganese',
        'mn',
        'ferromanganese 2',
        '4% carbon',
        'ferromanganese >4% carbon',
        'ferromanganese ≤1% carbon',
        'ferromanganese 1',
        '2% carbon',
        'silicomanganese',
    ],
    ("7202", "Molybdenum"): [
        'molybdenum',
        'mo',
        'ferromolybdenum',
        'ferroalloys',
    ],
    ("7202", "Nickel"): [
        'nickel',
        'ni',
        'ferronickel',
    ],
    ("7202", "Niobium"): [
        'niobium',
        'nb',
        'ferroniobium, <0.02% p or s, or <0.4% si',
        'ferroniobium, other',
    ],
    ("7202", "Silicon (Anode Grade)"): [
        'silicon (anode grade)',
        'si',
        'battery grade',
        'battery-grade',
        'high purity',
    ],
    ("7202", "Titanium"): [
        'titanium',
        'ti',
        'ferrotitanium and ferrosilicon titanium',
    ],
    ("7202", "Vanadium"): [
        'vanadium',
        'ferrovanadium',
    ],
    ("720211", "Manganese"): [
        'manganese',
        'mn',
        'ferromanganese 2',
        '4% carbon',
        'ferromanganese >4% carbon',
    ],
    ("720219", "Manganese"): [
        'manganese',
        'mn',
        'ferromanganese ≤1% carbon',
        'ferromanganese 1',
        '2% carbon',
    ],
    ("720221", "Silicon (Anode Grade)"): [
        'silicon (anode grade)',
        'si',
        'battery grade',
        'battery-grade',
        'high purity',
    ],
    ("720229", "Silicon (Anode Grade)"): [
        'silicon (anode grade)',
        'si',
        'battery grade',
        'battery-grade',
        'high purity',
    ],
    ("720230", "Manganese"): [
        'manganese',
        'mn',
        'silicomanganese',
    ],
    ("720241", "Chromium"): [
        'chromium',
        'cr',
        'ferrochromium >4% carbon',
    ],
    ("720249", "Chromium"): [
        'chromium',
        'cr',
        'ferrochromium 3',
        '4% carbon',
        'ferrochromium 0.5',
        '3% carbon',
        'ferrochromium ≤0.5% carbon',
    ],
    ("720260", "Nickel"): [
        'nickel',
        'ni',
        'ferronickel',
    ],
    ("720270", "Molybdenum"): [
        'molybdenum',
        'mo',
        'ferromolybdenum',
        'ferroalloys',
    ],
    ("720280", "Tungsten"): [
        'tungsten',
        'ferrotungsten and ferrosilicon tungsten',
    ],
    ("720291", "Titanium"): [
        'titanium',
        'ti',
        'ferrotitanium and ferrosilicon titanium',
    ],
    ("720292", "Vanadium"): [
        'vanadium',
        'ferrovanadium',
    ],
    ("720293", "Niobium"): [
        'niobium',
        'nb',
        'ferroniobium, <0.02% p or s, or <0.4% si',
        'ferroniobium, other',
    ],
    ("720299", "Zirconium"): [
        'zirconium',
        'zr',
        'ferrozirconium',
    ],
    ("7204", "Chromium"): [
        'chromium',
        'cr',
        'waste and scrap',
        'stainless‑steel scrap',
    ],
    ("720421", "Chromium"): [
        'chromium',
        'cr',
        'waste and scrap',
        'stainless‑steel scrap',
    ],
    ("7402", "Copper"): [
        'copper',
        'cu',
        'copper anodes for electrolytic refining',
    ],
    ("740200", "Copper"): [
        'copper',
        'cu',
        'copper anodes for electrolytic refining',
    ],
    ("7403", "Copper"): [
        'copper',
        'cu',
        'refined copper, unwrought',
    ],
    ("740311", "Copper"): [
        'copper',
        'cu',
    ],
    ("740319", "Copper"): [
        'copper',
        'cu',
    ],
    ("7404", "Copper"): [
        'copper',
        'cu',
        'waste and scrap',
        'copper scrap',
    ],
    ("740400", "Copper"): [
        'copper',
        'cu',
        'waste and scrap',
        'copper scrap',
    ],
    ("7408", "Copper"): [
        'copper',
        'cu',
        'copper wire rod',
    ],
    ("740811", "Copper"): [
        'copper',
        'cu',
        'copper wire rod',
    ],
    ("7501", "Nickel"): [
        'nickel',
        'ni',
    ],
    ("7502", "Nickel"): [
        'nickel',
        'ni',
        'unwrought nickel, not alloyed',
    ],
    ("750210", "Nickel"): [
        'nickel',
        'ni',
        'unwrought nickel, not alloyed',
    ],
    ("750220", "Nickel"): [
        'nickel',
        'ni',
    ],
    ("7503", "Nickel"): [
        'nickel',
        'ni',
        'waste and scrap',
        'nickel waste and scrap',
    ],
    ("750300", "Nickel"): [
        'nickel',
        'ni',
        'waste and scrap',
        'nickel waste and scrap',
    ],
    ("7601", "Aluminum"): [
        'aluminum',
        'al',
        'aluminum, not alloyed',
        'in coils',
        '>99.9%',
        '99.8\n99.9%',
        'aluminum alloys, unwrought',
        'billet',
    ],
    ("760110", "Aluminum"): [
        'aluminum',
        'al',
        'aluminum, not alloyed',
        'in coils',
        '>99.9%',
        '99.8\n99.9%',
    ],
    ("760120", "Aluminum"): [
        'aluminum',
        'al',
        'aluminum alloys, unwrought',
        'billet',
    ],
    ("7602", "Aluminum"): [
        'aluminum',
        'al',
        'waste and scrap',
        'aluminum scrap',
        'used beverage container scrap',
        'industrial process scrap',
    ],
    ("760200", "Aluminum"): [
        'aluminum',
        'al',
        'waste and scrap',
        'aluminum scrap',
        'used beverage container scrap',
        'industrial process scrap',
    ],
    ("7901", "Zinc"): [
        'zinc',
        'zn',
        'unwrought zinc, not alloyed, containing 99.99% or more zinc',
        'unwrought zinc, not alloyed, <99.99% zinc, casting‑grade',
        'unwrought zinc, not alloyed, other',
        'zinc alloys',
    ],
    ("7902", "Zinc"): [
        'zinc',
        'zn',
        'waste and scrap',
        'zinc waste and scrap',
    ],
    ("790200", "Zinc"): [
        'zinc',
        'zn',
        'waste and scrap',
        'zinc waste and scrap',
    ],
    ("8001", "Tin"): [
        'tin',
        'sn',
        'tin, unwrought, not alloyed',
        'tin alloys, containing 5% or less lead',
        'tin alloys, containing >5% but ≤25% lead',
        'tin alloys, containing >25% lead',
    ],
    ("800110", "Tin"): [
        'tin',
        'sn',
        'tin, unwrought, not alloyed',
    ],
    ("800120", "Tin"): [
        'tin',
        'sn',
        'tin alloys, containing 5% or less lead',
        'tin alloys, containing >5% but ≤25% lead',
        'tin alloys, containing >25% lead',
    ],
    ("800200", "Tin"): [
        'tin',
        'sn',
        'waste and scrap',
        'tin waste and scrap',
    ],
    ("8101", "Tungsten"): [
        'tungsten',
        'tungsten powders',
        'tungsten waste and scrap',
    ],
    ("810110", "Tungsten"): [
        'tungsten',
        'tungsten powders',
    ],
    ("810194", "Tungsten"): [
        'tungsten',
    ],
    ("810197", "Tungsten"): [
        'tungsten',
        'waste and scrap',
        'tungsten waste and scrap',
    ],
    ("810199", "Tungsten"): [
        'tungsten',
    ],
    ("8102", "Molybdenum"): [
        'molybdenum',
        'mo',
        'molybdenum metal powders',
        'molybdenum metal, unwrought',
        'molybdenum wrought bars and rods',
        'molybdenum wrought plates, sheets, strips, and the like',
        'molybdenum wire',
        'molybdenum waste and scrap',
        'molybdenum, other forms',
    ],
    ("810210", "Molybdenum"): [
        'molybdenum',
        'mo',
        'molybdenum metal powders',
    ],
    ("810294", "Molybdenum"): [
        'molybdenum',
        'mo',
        'molybdenum metal, unwrought',
    ],
    ("810295", "Molybdenum"): [
        'molybdenum',
        'mo',
        'molybdenum wrought bars and rods',
        'molybdenum wrought plates, sheets, strips, and the like',
    ],
    ("810296", "Molybdenum"): [
        'molybdenum',
        'mo',
        'molybdenum wire',
    ],
    ("810297", "Molybdenum"): [
        'molybdenum',
        'mo',
        'waste and scrap',
        'molybdenum waste and scrap',
    ],
    ("810299", "Molybdenum"): [
        'molybdenum',
        'mo',
        'molybdenum, other forms',
    ],
    ("8103", "Tantalum"): [
        'tantalum',
        'ta',
        'tantalum, unwrought',
        'powders',
        'alloys and metal',
        'tantalum, waste and scrap',
    ],
    ("810320", "Tantalum"): [
        'tantalum',
        'ta',
        'tantalum, unwrought',
        'powders',
        'alloys and metal',
    ],
    ("810330", "Tantalum"): [
        'tantalum',
        'ta',
        'tantalum, waste and scrap',
    ],
    ("810391", "Tantalum"): [
        'tantalum',
        'ta',
        'waste and scrap',
    ],
    ("810399", "Tantalum"): [
        'tantalum',
        'ta',
    ],
    ("8104", "Magnesium"): [
        'magnesium',
        'mg',
        'unwrought magnesium metal',
        'unwrought magnesium alloys',
        'magnesium powders and granules',
        'wrought magnesium',
    ],
    ("810411", "Magnesium"): [
        'magnesium',
        'mg',
        'unwrought magnesium metal',
    ],
    ("810419", "Magnesium"): [
        'magnesium',
        'mg',
        'unwrought magnesium alloys',
    ],
    ("810420", "Magnesium"): [
        'magnesium',
        'mg',
        'waste and scrap',
    ],
    ("810430", "Magnesium"): [
        'magnesium',
        'mg',
        'magnesium powders and granules',
    ],
    ("810490", "Magnesium"): [
        'magnesium',
        'mg',
        'wrought magnesium',
    ],
    ("8105", "Cobalt"): [
        'cobalt',
        'co',
        'unwrought cobalt, alloys',
        'unwrought cobalt, other',
        'cobalt mattes',
        'powders',
        'cobalt waste and scrap',
        'wrought cobalt articles',
    ],
    ("810520", "Cobalt"): [
        'cobalt',
        'co',
        'unwrought cobalt, alloys',
        'unwrought cobalt, other',
        'cobalt mattes',
        'powders',
    ],
    ("810530", "Cobalt"): [
        'cobalt',
        'co',
        'cobalt waste and scrap',
    ],
    ("810590", "Cobalt"): [
        'cobalt',
        'co',
        'waste and scrap',
        'wrought cobalt articles',
    ],
    ("8106", "Bismuth"): [
        'bismuth',
        'bi',
        'and articles',
        '>99.99%',
        'bismuth and articles, other',
    ],
    ("810610", "Bismuth"): [
        'bismuth',
        'bi',
        'and articles',
        '>99.99%',
    ],
    ("810690", "Bismuth"): [
        'bismuth',
        'bi',
        'bismuth and articles, other',
    ],
    ("8108", "Titanium"): [
        'titanium',
        'ti',
        'titanium, unwrought',
        'titanium waste and scrap',
        'other titanium metal articles',
        'wrought titanium metal',
    ],
    ("810820", "Titanium"): [
        'titanium',
        'ti',
        'titanium, unwrought',
    ],
    ("810830", "Titanium"): [
        'titanium',
        'ti',
        'waste and scrap',
        'titanium waste and scrap',
    ],
    ("810890", "Titanium"): [
        'titanium',
        'ti',
        'other titanium metal articles',
        'wrought titanium metal',
    ],
    ("8109", "Zirconium"): [
        'zirconium',
        'zr',
        'zirconium, unwrought',
        'zirconium powders',
        'zirconium waste and scrap',
        'zirconium waste and scrap, other',
        'other zirconium articles',
        'other zirconium articles, other',
    ],
    ("810921", "Zirconium"): [
        'zirconium',
        'zr',
        'zirconium, unwrought',
    ],
    ("810929", "Zirconium"): [
        'zirconium',
        'zr',
        'zirconium powders',
    ],
    ("810931", "Zirconium"): [
        'zirconium',
        'zr',
        'waste and scrap',
        'zirconium waste and scrap',
    ],
    ("810939", "Zirconium"): [
        'zirconium',
        'zr',
        'waste and scrap',
        'zirconium waste and scrap, other',
    ],
    ("810991", "Zirconium"): [
        'zirconium',
        'zr',
        'other zirconium articles',
    ],
    ("810999", "Zirconium"): [
        'zirconium',
        'zr',
        'other zirconium articles, other',
    ],
    ("8110", "Antimony"): [
        'antimony',
        'sb',
        'unwrought antimony',
        'powders',
        'waste and scrap',
        'antimony articles',
    ],
    ("811010", "Antimony"): [
        'antimony',
        'sb',
        'unwrought antimony',
        'powders',
    ],
    ("811020", "Antimony"): [
        'antimony',
        'sb',
        'waste and scrap',
    ],
    ("811090", "Antimony"): [
        'antimony',
        'sb',
        'antimony articles',
    ],
    ("8111", "Manganese"): [
        'manganese',
        'mn',
        'manganese metal ≥99.5%',
        'manganese metal, other',
    ],
    ("811100", "Manganese"): [
        'manganese',
        'mn',
        'manganese metal ≥99.5%',
        'manganese metal, other',
    ],
    ("8112", "Chromium"): [
        'chromium',
        'cr',
        'chromium metal, unwrought',
        'chromium waste and scrap',
        'chromium metal, other',
    ],
    ("8112", "Gallium"): [
        'gallium',
        'ga',
        'gallium metal',
    ],
    ("8112", "Germanium"): [
        'germanium',
        'ge',
        'germanium metal, unwrought',
        'germanium metal, powder',
        'germanium metal, wrought',
    ],
    ("8112", "Indium"): [
        'indium',
        'in',
        'unwrought indium, incl. powders',
    ],
    ("8112", "Niobium"): [
        'niobium',
        'nb',
        'niobium waste and scrap',
        'niobium powders and unwrought metal',
        'niobium, other forms',
    ],
    ("8112", "Rhenium"): [
        'rhenium',
        're',
        'rhenium, unwrought',
        'waste and scrap',
        'powders',
    ],
    ("811221", "Chromium"): [
        'chromium',
        'cr',
        'chromium metal, unwrought',
    ],
    ("811222", "Chromium"): [
        'chromium',
        'cr',
        'waste and scrap',
        'chromium waste and scrap',
    ],
    ("811229", "Chromium"): [
        'chromium',
        'cr',
        'chromium metal, other',
    ],
    ("811241", "Rhenium"): [
        'rhenium',
        're',
        'rhenium, unwrought',
        'waste and scrap',
        'powders',
    ],
    ("811292", "Gallium"): [
        'gallium',
        'ga',
        'gallium metal',
    ],
    ("811292", "Germanium"): [
        'germanium',
        'ge',
        'germanium metal, unwrought',
        'germanium metal, powder',
    ],
    ("811292", "Indium"): [
        'indium',
        'in',
        'unwrought indium, incl. powders',
    ],
    ("811292", "Niobium"): [
        'niobium',
        'nb',
        'niobium waste and scrap',
        'niobium powders and unwrought metal',
    ],
    ("811292", "Vanadium"): [
        'vanadium',
        'vanadium metal',
    ],
    ("811299", "Germanium"): [
        'germanium',
        'ge',
        'germanium metal, wrought',
    ],
    ("811299", "Niobium"): [
        'niobium',
        'nb',
        'niobium, other forms',
    ],
    ("811299", "Vanadium"): [
        'vanadium',
        'vanadium and articles thereof',
    ],
}
